import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDownToLine, ArrowLeft, ArrowRight, Check, ChevronRight, CircleHelp, Copy, Crown, Diamond, Eye, Flame, Snowflake, Sun, Waves, Mountain, Zap, Orbit, Layers3, Link, LoaderCircle, Plus, RotateCcw, Shield, Sparkles, Swords, Trash2, Users, Wifi, X } from 'lucide-react';
import { createRoom, csv, stats, VALUES, type Value, type PointValue, type Room } from './game';
import { useRoom, type Session } from './useRoom';
import { useAgentTools } from './useAgentTools';
import { StoryOverview } from './StoryOverview';
import { CREATURES } from './creatures';
import './style.css';

const roomId = new URLSearchParams(location.search).get('room');
const validRoom = roomId && /^[a-f0-9-]{36}$/.test(roomId) ? roomId : null;
function stored(key: string) { try { return sessionStorage.getItem(key); } catch { return null; } }
function save(key: string, value: string) { try { sessionStorage.setItem(key, value); } catch { /* Browser storage is optional. */ } }
function recover(): Session | null {
  if (!validRoom) return null;
  try {
    const raw = stored('shodown-host-' + validRoom);
    if (!raw) return null;
    const room = JSON.parse(raw) as Room;
    if (room.id !== validRoom || !Array.isArray(room.stories) || !room.members.some(m => m.id === room.hostId)) return null;
    room.members = room.members.map(m => ({ ...m, online: m.host }));
    room.credentials ??= {};
    return { roomId: room.id, userId: room.hostId, name: room.members.find(m => m.host)!.name, host: true, initial: room };
  } catch { return null; }
}
const creatureIcons = { nature: Shield, arcane: Sparkles, fire: Flame, frost: Snowflake, solar: Sun, ocean: Waves, magma: Mountain, storm: Zap, cosmic: Orbit };
function CreatureCard({ value, decorative = false, selected = false, onClick, disabled = false }: { value: PointValue; decorative?: boolean; selected?: boolean; onClick?: () => void; disabled?: boolean }) {
  const creature = CREATURES[value];
  const Icon = creatureIcons[creature.cls as keyof typeof creatureIcons];
  const content = <><div className="card-top"><span>{creature.name}</span><Icon size={13}/></div><div className={'creature-art art-' + creature.panel} style={{ backgroundImage: `url("${creature.sheet}")`, backgroundPositionY: creature.positionY ?? '33%' }}/><div className="card-element"><span>{creature.element}</span><span aria-label={`${creature.stars} krachtsterren`}>{Array(creature.stars).fill('✦').join(' ')}</span></div><div className="card-value">{value}<span>STORY POINTS</span></div><div className="card-bottom"><span>{selected ? 'GEKOZEN' : 'SUMMON YOUR ESTIMATE'}</span>{selected ? <Check size={12}/> : <Diamond size={10}/>}</div></>;
  return decorative ? <div className={'creature-card decorative ' + creature.cls}>{content}</div> : <button type="button" className={'creature-card ' + creature.cls + (selected ? ' selected' : '')} onClick={onClick} disabled={disabled} title={`${creature.name} · ${value} story points`} aria-label={`${value} story points kiezen — ${creature.name}`} aria-pressed={selected}>{content}</button>;
}
function Modal({ title, children, close }: { title: string; children: React.ReactNode; close: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { ref.current?.showModal(); return () => ref.current?.close(); }, []);
  return <dialog ref={ref} onCancel={close} onClick={e => { if (e.target === e.currentTarget) close(); }}><div className="modal-head"><h2>{title}</h2><button className="icon-btn" onClick={close} aria-label="Sluiten"><X size={20}/></button></div>{children}</dialog>;
}
function App() {
  const [session, setSession] = useState<Session | null>(recover);
  const { room, connected, status, error, act, retry } = useRoom(session);
  const [name, setName] = useState(stored('shodown-name') ?? '');
  const [roomName, setRoomName] = useState('');
  const [dialog, setDialog] = useState<'story' | 'help' | 'leave' | 'delete' | 'restart' | 'share' | null>(null);
  const [toast, setToast] = useState('');
  const [title, setTitle] = useState('');
  const [reference, setReference] = useState('');
  const [description, setDescription] = useState('');
  const [estimate, setEstimate] = useState<Value>('5');
  const [view, setView] = useState<'arena' | 'results'>('arena');
  useAgentTools(room, session?.host ?? false, connected, () => setDialog('story'));
  const active = room?.stories.find(s => s.id === room.activeId);
  const result = active ? stats(active) : null;
  const ownVote = session && active ? active.votes[session.userId] : undefined;
  const online = room?.members.filter(m => m.online) ?? [];
  const voted = active ? online.filter(m => Object.hasOwn(active.votes, m.id)).length : 0;
  const completed = room?.stories.filter(s => s.estimate !== null).length ?? 0;
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(''), 3200); return () => clearTimeout(timer); } }, [toast]);
  useEffect(() => { if (active?.estimate) setEstimate(active.estimate); else setEstimate('5'); }, [active?.id, active?.estimate]);
  useEffect(() => {
    if (!session?.host) return;
    const warn = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ''; };
    window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn);
  }, [session]);
  function start(event: React.FormEvent) {
    event.preventDefault();
    if (!name.trim()) return;
    save('shodown-name', name.trim());
    const userId = stored('shodown-user') ?? crypto.randomUUID();
    save('shodown-user', userId);
    const token = stored('shodown-token') ?? crypto.randomUUID();
    save('shodown-token', token);
    if (validRoom) { setSession({ roomId: validRoom, userId, name: name.trim(), host: false, token }); return; }
    const id = crypto.randomUUID();
    const initial = createRoom(id, userId, roomName.trim() || 'De refinement arena', name.trim());
    save('shodown-host-' + id, JSON.stringify(initial));
    history.replaceState(null, '', '?room=' + id);
    setSession({ roomId: id, userId, name: name.trim(), host: true, initial });
  }
  async function share() {
    try { await navigator.clipboard.writeText(location.origin + '/?room=' + session!.roomId); setToast('Kamerlink gekopieerd. Nodig je team uit!'); }
    catch { setDialog('share'); }
  }
  function addStory(event: React.FormEvent) {
    event.preventDefault();
    act({ type: 'add', title, reference, description }); setDialog(null); setTitle(''); setReference(''); setDescription(''); setView('arena');
  }
  function download() {
    if (!room) return;
    const url = URL.createObjectURL(new Blob([csv(room)], { type: 'text/csv;charset=utf-8;' }));
    const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'story-point-shodown-resultaten.csv'; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  const nextStory = room?.stories.find(s => s.id !== active?.id && s.estimate === null);
  return <div className="app">
    <header className="topbar"><a href="/" className="brand" onClick={e => { if (session) { e.preventDefault(); setDialog('leave'); } }} aria-label="Story Point Shodown startpagina"><div className="brand-symbol"><Swords size={25}/></div><div><span>STORY POINT</span><strong>SHODOWN<span className="brand-star">✦</span></strong></div></a><div className="header-right"><span className="edition">THE PLANNING POKER ARENA</span><button className="icon-btn" aria-label="Hoe werkt het?" onClick={() => setDialog('help')}><CircleHelp size={20}/></button>{session && <button className="user-badge" onClick={() => setDialog('leave')} title="Kamer verlaten"><span className="avatar">{session.name.slice(0, 1).toUpperCase()}</span><span>{session.name}</span></button>}</div></header>
    {!session ? <main className="lobby"><div className="lobby-content"><div className="eyebrow"><span className="tiny-diamond"/> JOUW TEAM. JOUW KAARTEN.</div><h1>Grote ideeën.<br/>Magische <em>inschattingen.</em></h1><p className="lobby-intro">Leg je kaarten op tafel. Schat samen stories in en ontdek waar jullie op één lijn zitten.</p><section className="create-panel"><div className="panel-title"><Swords size={20}/><h2>{validRoom ? 'Sluit je aan bij het duel' : 'Open jouw arena'}</h2></div><form onSubmit={start}><label>Jouw naam<input autoFocus required maxLength={30} placeholder="Hoe mogen we je noemen?" value={name} onChange={e => setName(e.target.value)}/></label>{!validRoom && <label>Naam van de kamer <span className="optional">optioneel</span><input maxLength={70} placeholder="Bijv. Team Phoenix · Sprint 24" value={roomName} onChange={e => setRoomName(e.target.value)}/></label>}<button className="button primary large" type="submit">{validRoom ? 'Betreed de arena' : 'Maak een kamer'}<ArrowRight size={18}/></button></form><div className="create-note"><Shield size={14}/><span>Geen account nodig. Deel de link en speel.</span></div>{roomId && !validRoom && <p role="alert" className="inline-error">Deze kamerlink is ongeldig. Maak een nieuwe kamer.</p>}</section><div className="lobby-footnote"><span className="live-dot"/> Live met je team<span className="dot-divider">·</span>Geen database<span className="dot-divider">·</span>9 unieke creatures</div></div><div className="lobby-visual"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="art-caption"><span>✦</span> CHOOSE YOUR CREATURE <span>✦</span></div><div className="display-deck"><CreatureCard value="3" decorative/><CreatureCard value="5" decorative/><CreatureCard value="8" decorative/></div><div className="visual-bottom"><div className="small-rule"/><Sparkles size={18}/><span>Elke inschatting heeft z’n eigen kracht.</span><div className="small-rule"/></div><div className="session-notice"><Wifi size={16}/><p>Jouw browser houdt de kamer open.<br/><span>Blijf verbonden zolang jullie samen stemmen.</span></p></div></div></main>
    : !room ? <main className="connecting"><div className="connection-symbol"><Swords size={36}/></div><h1>{error ? 'Nog geen verbinding' : 'De arena wordt geopend'}</h1><p>{error || status}</p>{error ? <button className="button primary" onClick={retry}><RotateCcw size={16}/>Opnieuw verbinden</button> : <LoaderCircle className="spin"/>}<button className="text-button" onClick={() => location.assign('/')}>Terug naar het begin</button></main>
    : <main className="workspace"><div className="room-heading"><div><div className="eyebrow"><span className="live-dot"/> LIVE SESSIE</div><h1>{room.name}</h1><div className="room-meta"><span><Users size={14}/>{online.length} {online.length === 1 ? 'deelnemer' : 'deelnemers'}</span><span className="dot-divider">·</span><span>{completed} van {room.stories.length} stories ingeschat</span></div></div><button className="button primary" onClick={share} disabled={!connected}><Link size={16}/>Nodig je team uit<Copy size={15}/></button></div>
    {error && <div className="connection-error" role="alert"><Wifi size={18}/><span>{error}</span><button className="button small" onClick={retry}>Opnieuw verbinden</button></div>}
    <div className="workspace-grid"><aside className="story-sidebar"><div className="sidebar-title"><h2><Layers3 size={17}/>Stories</h2><span className="counter">{room.stories.length}</span></div><div className="story-list">{room.stories.length === 0 && <div className="sidebar-empty"><Layers3 size={28}/><p>Een nieuw hoofdstuk.<br/>Voeg je eerste story toe.</p></div>}{room.stories.map((story, index) => <button className={'story-item ' + (active?.id === story.id ? 'active' : '')} key={story.id} disabled={!session.host || !connected} onClick={() => { act({ type: 'select', id: story.id }); setView('arena'); }}><div className="story-item-top"><span>{story.reference || `STORY ${String(index + 1).padStart(2, '0')}`}</span>{story.estimate !== null ? <span className="story-estimate">{story.estimate}<Check size={11}/></span> : active?.id === story.id ? <span className="current-tag">ACTIEF</span> : <span className="waiting-dot"/>}</div><strong>{story.title}</strong><span className="story-item-sub">{story.estimate !== null ? 'Ingeschat' : story.revealed ? 'Kaarten onthuld' : Object.keys(story.votes).length ? 'Stemronde bezig' : 'Klaar voor het duel'}{active?.id === story.id && <ChevronRight size={14}/>}</span></button>)}</div>{session.host && <button className="add-story" onClick={() => setDialog('story')} disabled={!connected || room.stories.length >= 100}><Plus size={17}/>Story toevoegen</button>}<div className="sidebar-bottom"><div className="progress-label"><span>Sessievoortgang</span><strong>{completed}/{room.stories.length}</strong></div><div className="progress-track"><span style={{ width: `${room.stories.length ? completed / room.stories.length * 100 : 0}%` }}/></div><button className="text-button" disabled={!room.stories.length} onClick={() => setView(view === 'results' ? 'arena' : 'results')}><ArrowDownToLine size={15}/>{view === 'results' ? 'Terug naar de arena' : 'Alle stories & stemmen'}</button></div></aside>
    <div className="arena-column"><div className="arena-tabs"><button className={view === 'arena' ? 'active' : ''} onClick={() => setView('arena')}><Swords size={16}/>De arena</button><button className={view === 'results' ? 'active' : ''} onClick={() => setView('results')}><Layers3 size={16}/>Stories & stemmen{completed > 0 && <span className="counter">{completed}</span>}</button><span className="private-label"><Shield size={13}/>Jullie eigen kamer</span></div>
    {view === 'results' ? <section className="results-panel"><div className="section-head"><div><span className="eyebrow">STORY VOOR STORY</span><h2>Alle inschattingen</h2></div><button className="button small" onClick={download} disabled={!room.stories.length}><ArrowDownToLine size={15}/>Download CSV</button></div>{room.stories.length ? <StoryOverview room={room} userId={session.userId} canSelect={session.host && connected} onSelect={id => { act({ type: 'select', id }); setView('arena'); }}/> : <p className="muted">Voeg een story toe om met je team te beginnen.</p>}<p className="results-note">Alleen onthulde stemmen worden geëxporteerd. Download de resultaten voordat je de kamer sluit.</p></section>
    : active ? <><section className="active-story"><div className="section-head"><div className="story-kicker"><span>{active.reference || `STORY ${String(room.stories.indexOf(active) + 1).padStart(2, '0')}`}</span><span className={'status-pill ' + (active.revealed ? 'revealed' : '')}>{active.estimate !== null ? 'Ingeschat' : active.revealed ? 'Kaarten onthuld' : 'Stemronde open'}</span></div>{session.host && <button className="icon-btn" onClick={() => setDialog('delete')} aria-label="Actieve story verwijderen" disabled={!connected}><Trash2 size={16}/></button>}</div><h2>{active.title}</h2>{active.description && <p className="story-description">{active.description}</p>}<div className="story-bottom"><span><Layers3 size={14}/>Story points · 0,5 – 40</span><span>{active.revealed ? 'Tijd om te bespreken' : 'Kies je kaart hieronder'}</span></div></section>
    <section className="duel-table"><div className="table-heading"><h3>{active.revealed ? 'De kaarten liggen op tafel' : 'Het team verzamelt zijn krachten'}</h3><span>{voted}/{online.length} gestemd</span></div><div className="players">{room.members.map((member, i) => { const hasVoted = Object.hasOwn(active.votes, member.id); return <div className={'player ' + (!member.online ? 'offline' : '')} key={member.id}><div className={'player-card ' + (active.revealed && hasVoted ? 'face-up' : hasVoted ? 'locked' : 'empty')}><div className="player-card-inner">{active.revealed && hasVoted ? <strong>{active.votes[member.id]}</strong> : hasVoted ? <><Diamond size={29}/><Check className="vote-check" size={13}/></> : <span>?</span>}</div></div><div className="player-name"><span className={'avatar avatar-' + i % 4}>{member.name.slice(0, 1).toUpperCase()}</span><span>{member.name}{member.id === session.userId && <small> (jij)</small>}</span>{member.host && <Crown size={12}/>}</div><span className={'player-status ' + (hasVoted ? 'ready' : '')}>{!member.online ? 'Offline' : active.revealed ? hasVoted ? 'Onthuld' : 'Niet gestemd' : hasVoted ? 'Kaart gekozen' : 'Kiest een kaart…'}</span></div>; })}{room.members.length === 1 && <button className="invite-seat" onClick={share}><div><Plus size={20}/></div><span>Nodig iemand uit</span></button>}</div>
    {active.revealed && result ? <div className="reveal-summary"><div className="average"><span>Gemiddelde</span><strong>{result.average}<small>punten</small></strong></div><div className="discussion"><Sparkles size={20}/><div><strong>{result.consensus ? 'Jullie zitten op één lijn!' : result.count > 1 && result.min !== result.max ? 'Verschillende kaarten, goed gesprek.' : 'Bespreek jullie inschatting.'}</strong><p>{result.count > 1 && result.min !== result.max ? `Van ${result.min?.toLocaleString('nl-NL')} tot ${result.max?.toLocaleString('nl-NL')} punten. Wat zien jullie anders?` : 'Kies samen het definitieve aantal story points.'}</p></div></div></div> : <div className="hidden-note"><Shield size={14}/>Stemmen blijven geheim tot de onthulling.</div>}
    <div className="table-controls">{session.host ? active.revealed ? <><button className="button small ghost" onClick={() => setDialog('restart')} disabled={!connected}><RotateCcw size={15}/>Opnieuw stemmen</button><div className="estimate-controls"><label htmlFor="estimate">Definitief</label><select id="estimate" value={estimate} onChange={e => setEstimate(e.target.value as Value)} disabled={!connected}>{VALUES.map(v => <option key={v}>{v}</option>)}</select><button className="button primary small" disabled={!connected} onClick={() => { act({ type: 'estimate', value: estimate }); setToast('Inschatting opgeslagen'); }}><Check size={15}/>{active.estimate !== null ? 'Bijwerken' : 'Vastleggen'}</button></div></> : <><span className="control-caption">{voted === online.length && online.length > 1 ? 'Iedereen is klaar. Laat de kaarten zien!' : 'Onthul wanneer jullie klaar zijn.'}</span><button className="button primary" onClick={() => act({ type: 'reveal' })} disabled={!connected || !Object.keys(active.votes).length}><Eye size={16}/>Onthul de kaarten</button></> : <p className="control-caption">{active.revealed ? 'De sessieleider legt jullie gezamenlijke inschatting vast.' : 'De sessieleider onthult de kaarten zodra jullie klaar zijn.'}</p>}</div>{session.host && active.estimate !== null && nextStory && <button className="next-story" onClick={() => act({ type: 'select', id: nextStory.id })} disabled={!connected}>Volgende story: {nextStory.title}<ArrowRight size={16}/></button>}</section>
    <section className={'your-hand ' + (active.revealed ? 'hand-complete' : '')}><div className="hand-heading"><div><span className="eyebrow">JOUW HAND</span><h2>{active.revealed ? 'Een goed gesprek is de echte winst.' : 'Welke kracht past bij deze story?'}</h2></div><span className="hand-selection">{active.revealed ? <><Check size={14}/>Stemronde gesloten</> : ownVote !== undefined && ownVote !== null ? <><Check size={14}/>Je koos {ownVote}</> : 'Kies één kaart'}</span></div><div className="hand-cards">{VALUES.map(value => value === '?' || value === '☕' ? <button key={value} className={'special-card ' + (ownVote === value ? 'selected' : '')} disabled={active.revealed || !connected} aria-pressed={ownVote === value} aria-label={value === '?' ? 'Ik weet het nog niet' : 'Ik heb pauze nodig'} onClick={() => act({ type: 'vote', storyId: active.id, round: active.round, value })}><strong>{value}</strong><span>{value === '?' ? 'Twijfel' : 'Pauze'}</span></button> : <CreatureCard key={value} value={value} selected={ownVote === value} disabled={active.revealed || !connected} onClick={() => act({ type: 'vote', storyId: active.id, round: active.round, value })}/>)}</div><p className="hand-note">{active.revealed ? 'Klaar voor de volgende uitdaging?' : 'Je kunt je kaart veranderen tot de kaarten worden onthuld.'}</p></section></>
    : <section className="empty-arena"><div className="empty-symbol"><Swords size={34}/></div><span className="eyebrow">DE ARENA IS VAN JULLIE</span><h2>{session.host ? 'Elke quest begint met een story.' : 'Je bent erbij. Het duel kan beginnen.'}</h2><p>{session.host ? 'Voeg jullie eerste story toe en nodig je team uit. Daarna kiest iedereen in het geheim een kaart.' : 'De sessieleider voegt de stories toe. Jouw kaarten verschijnen zodra er een story klaarstaat.'}</p><div className="empty-actions">{session.host && <button className="button primary" onClick={() => setDialog('story')} disabled={!connected}><Plus size={17}/>Eerste story toevoegen</button>}<button className="button" onClick={share} disabled={!connected}><Link size={16}/>Deel de kamer</button></div><div className="mini-deck"><CreatureCard value="3" decorative/><CreatureCard value="5" decorative/><CreatureCard value="8" decorative/></div></section>}
    </div></div><footer className="room-footer"><span><span className={'live-dot ' + (!connected ? 'disconnected' : '')}/>{status}</span><span>{session.host ? 'Jij bent de sessieleider. Houd dit tabblad open.' : 'Deze kamer blijft beschikbaar zolang de sessieleider verbonden is.'}</span><button className="text-button" onClick={() => setDialog('leave')}><ArrowLeft size={13}/>Verlaat kamer</button></footer></main>}
    {!session && <footer className="lobby-footer"><span>BUILT FOR TEAMS. POWERED BY CREATURES.</span><span>Story Point Shodown <Diamond size={10}/> Laat de kaarten spreken.</span></footer>}
    {dialog === 'story' && <Modal title="Een nieuwe story" close={() => setDialog(null)}><form onSubmit={addStory}><label>Storytitel<input autoFocus required value={title} maxLength={160} onChange={e => setTitle(e.target.value)} placeholder="Bijv. Redesign van de gebruikerservaring"/></label><label>Referentie <span className="optional">optioneel</span><input value={reference} maxLength={30} onChange={e => setReference(e.target.value)} placeholder="Bijv. STORY-123"/></label><label>Beschrijving <span className="optional">optioneel</span><textarea value={description} maxLength={2000} rows={4} onChange={e => setDescription(e.target.value)} placeholder="Wat moet er gebeuren? Welke context heeft je team nodig?"/></label><button className="button primary large" type="submit" disabled={!connected}><Plus size={16}/>Voeg story toe</button></form></Modal>}
    {dialog === 'help' && <Modal title="Zo werkt het duel" close={() => setDialog(null)}><ol className="help-steps"><li><strong>Open een kamer</strong><p>Vul je naam in en deel de unieke kamerlink met je collega’s. Iedereen met de link kan meedoen.</p></li><li><strong>Voeg stories toe en kies een kaart</strong><p>De sessieleider kiest de actieve story. Iedereen stemt met story points van 0,5 tot 40, ? voor twijfel of ☕ voor pauze.</p></li><li><strong>Onthul, bespreek en leg vast</strong><p>Bekijk de verschillen en kies samen de definitieve inschatting. Ga door naar de volgende story.</p></li></ol><div className="help-note"><Wifi size={19}/><p>Geen database: de sessieleider bewaart de sessie in dit tabblad. Houd het open en download de resultaten voordat je sluit. Sluit je dit tabblad, dan vervalt de kamer. Sommige bedrijfsnetwerken of VPN’s blokkeren directe verbindingen.</p></div></Modal>}
    {dialog === 'leave' && <Modal title="De kamer verlaten?" close={() => setDialog(null)}><p>{session?.host ? 'Jij houdt deze kamer open. Als je vertrekt, verliezen je collega’s de verbinding. Download eerst de resultaten als je ze wilt bewaren.' : 'Je verlaat de kamer. Je kunt opnieuw meedoen via dezelfde link zolang de sessieleider verbonden is.'}</p><div className="modal-actions">{room && <button className="button" onClick={download}><ArrowDownToLine size={15}/>Download resultaten</button>}<button className="button primary" onClick={() => location.assign('/')}>Verlaat kamer</button></div></Modal>}
    {dialog === 'delete' && <Modal title="Story verwijderen?" close={() => setDialog(null)}><p>‘{active?.title}’ en alle bijbehorende stemmen worden uit de kamer verwijderd.</p><div className="modal-actions"><button className="button" onClick={() => setDialog(null)}>Annuleren</button><button className="button danger" disabled={!connected} onClick={() => { if (active) act({ type: 'remove', id: active.id }); setDialog(null); }}>Verwijderen</button></div></Modal>}
    {dialog === 'restart' && <Modal title="Een nieuwe stemronde?" close={() => setDialog(null)}><p>De huidige stemmen en definitieve inschatting voor deze story worden gewist. Iedereen kiest opnieuw in het geheim.</p><div className="modal-actions"><button className="button" onClick={() => setDialog(null)}>Annuleren</button><button className="button primary" disabled={!connected} onClick={() => { act({ type: 'restart' }); setDialog(null); }}>Opnieuw stemmen</button></div></Modal>}
    {dialog === 'share' && <Modal title="Nodig je team uit" close={() => setDialog(null)}><label>Kopieer deze kamerlink<input readOnly value={location.origin + '/?room=' + session?.roomId} onFocus={e => e.target.select()}/></label><p>Iedereen met deze link kan meedoen terwijl jij de kamer openhoudt.</p></Modal>}
    <div className={'toast ' + (toast ? 'visible' : '')} role="status" aria-live="polite">{toast && <><Check size={17}/>{toast}</>}</div>
  </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
