import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDownToLine, ArrowLeft, ArrowRight, Check, ChevronRight, CircleHelp, Copy, Crown, Diamond, Eye, Flame, Snowflake, Sun, Waves, Mountain, Zap, Orbit, Layers3, Link, LoaderCircle, Plus, RotateCcw, Shield, Sparkles, Swords, Trash2, Users, Wifi, X } from 'lucide-react';
import { createRoom, csv, stats, formatPoint, VALUES, POINT_VALUES, type Value, type PointValue, type Room } from './game';
import { useRoom, type Session } from './useRoom';
import { useAgentTools } from './useAgentTools';
import { StoryOverview } from './StoryOverview';
import { CREATURES } from './creatures';
import './style.css';

const roomId = new URLSearchParams(location.search).get('room');
const validRoom = roomId && /^[a-f0-9-]{36}$/.test(roomId) ? roomId : null;
function stored(key: string) { try { return sessionStorage.getItem(key); } catch { return null; } }
function save(key: string, value: string) { try { sessionStorage.setItem(key, value); } catch { /* Browser storage is optional. */ } }
function recover(): Session | null {
  if (!validRoom) return null;
  try {
    const raw = stored('shodown-host-' + validRoom);
    if (!raw) return null;
    const room = JSON.parse(raw) as Room;
    if (room.id !== validRoom || !Array.isArray(room.stories) || !room.members.some(m => m.id === room.hostId)) return null;
    room.members = room.members.map(m => ({ ...m, online: m.host }));
    room.credentials ??= {};
    return { roomId: room.id, userId: room.hostId, name: room.members.find(m => m.host)!.name, host: true, initial: room };
  } catch { return null; }
}
const creatureIcons = { nature: Shield, arcane: Sparkles, fire: Flame, frost: Snowflake, solar: Sun, ocean: Waves, magma: Mountain, storm: Zap, cosmic: Orbit };
function CreatureCard({ value, decorative = false, selected = false, onClick, disabled = false }: { value: PointValue; decorative?: boolean; selected?: boolean; onClick?: () => void; disabled?: boolean }) {
  const creature = CREATURES[value];
  const Icon = creatureIcons[creature.cls as keyof typeof creatureIcons];
  const content = <><div className="card-top"><span>{creature.name}</span><Icon size={13}/></div><div className={'creature-art art-' + creature.panel} style={{ backgroundImage: `url("${creature.sheet}")`, backgroundPositionY: creature.positionY ?? '33%' }}/><div className="card-element"><span>{creature.element}</span><span aria-label={`${creature.stars} power stars`}>{Array(creature.stars).fill('✦').join(' ')}</span></div><div className="card-value">{formatPoint(value)}<span>STORY POINTS</span></div><div className="card-bottom"><span>{selected ? 'SELECTED' : 'SUMMON YOUR ESTIMATE'}</span>{selected ? <Check size={12}/> : <Diamond size={10}/>}</div></>;
  return decorative ? <div className={'creature-card decorative ' + creature.cls}>{content}</div> : <button type="button" className={'creature-card ' + creature.cls + (selected ? ' selected' : '')} onClick={onClick} disabled={disabled} title={`${creature.name} · ${formatPoint(value)} story points`} aria-label={`Select ${formatPoint(value)} story points — ${creature.name}`} aria-pressed={selected}>{content}</button>;
}
function Modal({ title, children, close }: { title: string; children: React.ReactNode; close: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { ref.current?.showModal(); return () => ref.current?.close(); }, []);
  return <dialog ref={ref} onCancel={close} onClick={e => { if (e.target === e.currentTarget) close(); }}><div className="modal-head"><h2>{title}</h2><button className="icon-btn" onClick={close} aria-label="Close"><X size={20}/></button></div>{children}</dialog>;
}
function App() {
  const [session, setSession] = useState<Session | null>(recover);
  const { room, connected, status, error, act, retry } = useRoom(session);
  const [name, setName] = useState(stored('shodown-name') ?? '');
  const [roomName, setRoomName] = useState('');
  const [dialog, setDialog] = useState<'story' | 'help' | 'leave' | 'delete' | 'restart' | 'share' | null>(null);
  const [toast, setToast] = useState('');
  const [title, setTitle] = useState('');
  const [reference, setReference] = useState('');
  const [description, setDescription] = useState('');
  const [estimate, setEstimate] = useState<Value>('5');
  const [view, setView] = useState<'arena' | 'results'>('arena');
  useAgentTools(room, session?.host ?? false, connected, () => setDialog('story'));
  const active = room?.stories.find(s => s.id === room.activeId);
  const result = active ? stats(active) : null;
  const ownVote = session && active ? active.votes[session.userId] : undefined;
  const online = room?.members.filter(m => m.online) ?? [];
  const voted = active ? online.filter(m => Object.hasOwn(active.votes, m.id)).length : 0;
  const completed = room?.stories.filter(s => s.estimate !== null).length ?? 0;
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(''), 3200); return () => clearTimeout(timer); } }, [toast]);
  useEffect(() => { if (active?.estimate) setEstimate(active.estimate); else setEstimate('5'); }, [active?.id, active?.estimate]);
  useEffect(() => {
    if (!session?.host) return;
    const warn = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ''; };
    window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn);
  }, [session]);
  function start(event: React.FormEvent) {
    event.preventDefault();
    if (!name.trim()) return;
    save('shodown-name', name.trim());
    const userId = stored('shodown-user') ?? crypto.randomUUID();
    save('shodown-user', userId);
    const token = stored('shodown-token') ?? crypto.randomUUID();
    save('shodown-token', token);
    if (validRoom) { setSession({ roomId: validRoom, userId, name: name.trim(), host: false, token }); return; }
    const id = crypto.randomUUID();
    const initial = createRoom(id, userId, roomName.trim() || 'The refinement arena', name.trim());
    save('shodown-host-' + id, JSON.stringify(initial));
    history.replaceState(null, '', '?room=' + id);
    setSession({ roomId: id, userId, name: name.trim(), host: true, initial });
  }
  async function share() {
    try { await navigator.clipboard.writeText(location.origin + '/?room=' + session!.roomId); setToast('Room link copied. Invite your team!'); }
    catch { setDialog('share'); }
  }
  function addStory(event: React.FormEvent) {
    event.preventDefault();
    act({ type: 'add', title, reference, description }); setDialog(null); setTitle(''); setReference(''); setDescription(''); setView('arena');
  }
  function download() {
    if (!room) return;
    const url = URL.createObjectURL(new Blob([csv(room)], { type: 'text/csv;charset=utf-8;' }));
    const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'story-point-shodown-results.csv'; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  const nextStory = room?.stories.find(s => s.id !== active?.id && s.estimate === null);
  return <div className="app">
    <header className="topbar"><a href="/" className="brand" onClick={e => { if (session) { e.preventDefault(); setDialog('leave'); } }} aria-label="Story Point Shodown home"><div className="brand-symbol"><Swords size={25}/></div><div><span>STORY POINT</span><strong>SHODOWN<span className="brand-star">✦</span></strong></div></a><div className="header-right"><span className="edition">THE PLANNING POKER ARENA</span><button className="icon-btn" aria-label="How does it work?" onClick={() => setDialog('help')}><CircleHelp size={20}/></button>{session && <button className="user-badge" onClick={() => setDialog('leave')} title="Leave room"><span className="avatar">{session.name.slice(0, 1).toUpperCase()}</span><span>{session.name}</span></button>}</div></header>
    {!session ? <main className="lobby"><div className="lobby-content"><div className="eyebrow"><span className="tiny-diamond"/> YOUR TEAM. YOUR CARDS.</div><h1>Big ideas.<br/>Magical <em>estimates.</em></h1><p className="lobby-intro">Put your cards on the table. Estimate stories together and find out where your team agrees.</p><section className="create-panel"><div className="panel-title"><Swords size={20}/><h2>{validRoom ? 'Join the duel' : 'Open your arena'}</h2></div><form onSubmit={start}><label>Your name<input autoFocus required maxLength={30} placeholder="What should we call you?" value={name} onChange={e => setName(e.target.value)}/></label>{!validRoom && <label>Room name <span className="optional">optional</span><input maxLength={70} placeholder="e.g. Team Phoenix · Sprint 24" value={roomName} onChange={e => setRoomName(e.target.value)}/></label>}<button className="button primary large" type="submit">{validRoom ? 'Enter the arena' : 'Create a room'}<ArrowRight size={18}/></button></form><div className="create-note"><Shield size={14}/><span>No account needed. Share the link and play.</span></div>{roomId && !validRoom && <p role="alert" className="inline-error">This room link is invalid. Create a new room.</p>}</section><div className="lobby-footnote"><span className="live-dot"/> Live with your team<span className="dot-divider">·</span>No database<span className="dot-divider">·</span>9 unique creatures</div></div><div className="lobby-visual"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="art-caption"><span>✦</span> CHOOSE YOUR CREATURE <span>✦</span></div><div className="display-deck"><CreatureCard value="3" decorative/><CreatureCard value="5" decorative/><CreatureCard value="8" decorative/></div><div className="visual-bottom"><div className="small-rule"/><Sparkles size={18}/><span>Every estimate has its own power.</span><div className="small-rule"/></div><div className="session-notice"><Wifi size={16}/><p>Your browser keeps the room open.<br/><span>Stay connected while your team votes.</span></p></div></div></main>
    : !room ? <main className="connecting"><div className="connection-symbol"><Swords size={36}/></div><h1>{error ? 'Not connected yet' : 'Opening the arena'}</h1><p>{error || status}</p>{error ? <button className="button primary" onClick={retry}><RotateCcw size={16}/>Reconnect</button> : <LoaderCircle className="spin"/>}<button className="text-button" onClick={() => location.assign('/')}>Back to home</button></main>
    : <main className="workspace"><div className="room-heading"><div><div className="eyebrow"><span className="live-dot"/> LIVE SESSION</div><h1>{room.name}</h1><div className="room-meta"><span><Users size={14}/>{online.length} {online.length === 1 ? 'participant' : 'participants'}</span><span className="dot-divider">·</span><span>{completed} of {room.stories.length} stories estimated</span></div></div><button className="button primary" onClick={share} disabled={!connected}><Link size={16}/>Invite your team<Copy size={15}/></button></div>
    {error && <div className="connection-error" role="alert"><Wifi size={18}/><span>{error}</span><button className="button small" onClick={retry}>Reconnect</button></div>}
    <div className="workspace-grid"><aside className="story-sidebar"><div className="sidebar-title"><h2><Layers3 size={17}/>Stories</h2><span className="counter">{room.stories.length}</span></div><div className="story-list">{room.stories.length === 0 && <div className="sidebar-empty"><Layers3 size={28}/><p>A new chapter.<br/>Add your first story.</p></div>}{room.stories.map((story, index) => <button className={'story-item ' + (active?.id === story.id ? 'active' : '')} key={story.id} disabled={!session.host || !connected} onClick={() => { act({ type: 'select', id: story.id }); setView('arena'); }}><div className="story-item-top"><span>{story.reference || `STORY ${String(index + 1).padStart(2, '0')}`}</span>{story.estimate !== null ? <span className="story-estimate">{formatPoint(story.estimate)}<Check size={11}/></span> : active?.id === story.id ? <span className="current-tag">ACTIVE</span> : <span className="waiting-dot"/>}</div><strong>{story.title}</strong><span className="story-item-sub">{story.estimate !== null ? 'Estimated' : story.revealed ? 'Cards revealed' : Object.keys(story.votes).length ? 'Voting in progress' : 'Ready for the duel'}{active?.id === story.id && <ChevronRight size={14}/>}</span></button>)}</div>{session.host && <button className="add-story" onClick={() => setDialog('story')} disabled={!connected || room.stories.length >= 100}><Plus size={17}/>Add story</button>}<div className="sidebar-bottom"><div className="progress-label"><span>Session progress</span><strong>{completed}/{room.stories.length}</strong></div><div className="progress-track"><span style={{ width: `${room.stories.length ? completed / room.stories.length * 100 : 0}%` }}/></div><button className="text-button" disabled={!room.stories.length} onClick={() => setView(view === 'results' ? 'arena' : 'results')}><ArrowDownToLine size={15}/>{view === 'results' ? 'Back to the arena' : 'All stories & votes'}</button></div></aside>
    <div className="arena-column"><div className="arena-tabs"><button className={view === 'arena' ? 'active' : ''} onClick={() => setView('arena')}><Swords size={16}/>The arena</button><button className={view === 'results' ? 'active' : ''} onClick={() => setView('results')}><Layers3 size={16}/>Stories & votes{completed > 0 && <span className="counter">{completed}</span>}</button><span className="private-label"><Shield size={13}/>Your private room</span></div>
    {view === 'results' ? <section className="results-panel"><div className="section-head"><div><span className="eyebrow">STORY BY STORY</span><h2>All estimates</h2></div><button className="button small" onClick={download} disabled={!room.stories.length}><ArrowDownToLine size={15}/>Download CSV</button></div>{room.stories.length ? <StoryOverview room={room} userId={session.userId} canSelect={session.host && connected} onSelect={id => { act({ type: 'select', id }); setView('arena'); }}/> : <p className="muted">Add a story to get started with your team.</p>}<p className="results-note">Only revealed votes are exported. Download the results before closing the room.</p></section>
    : active ? <><section className="active-story"><div className="section-head"><div className="story-kicker"><span>{active.reference || `STORY ${String(room.stories.indexOf(active) + 1).padStart(2, '0')}`}</span><span className={'status-pill ' + (active.revealed ? 'revealed' : '')}>{active.estimate !== null ? 'Estimated' : active.revealed ? 'Cards revealed' : 'Voting open'}</span></div>{session.host && <button className="icon-btn" onClick={() => setDialog('delete')} aria-label="Delete active story" disabled={!connected}><Trash2 size={16}/></button>}</div><h2>{active.title}</h2>{active.description && <p className="story-description">{active.description}</p>}<div className="story-bottom"><span><Layers3 size={14}/>Story points · 0.5 – 40</span><span>{active.revealed ? 'Time to discuss' : 'Choose your card below'}</span></div></section>
    <section className="duel-table"><div className="table-heading"><h3>{active.revealed ? 'The cards are on the table' : 'Your team is gathering its strength'}</h3><span>{voted}/{online.length} voted</span></div><div className="players">{room.members.map((member, i) => { const hasVoted = Object.hasOwn(active.votes, member.id); return <div className={'player ' + (!member.online ? 'offline' : '')} key={member.id}><div className={'player-card ' + (active.revealed && hasVoted ? 'face-up' : hasVoted ? 'locked' : 'empty')}><div className="player-card-inner">{active.revealed && hasVoted ? <strong>{formatPoint(active.votes[member.id])}</strong> : hasVoted ? <><Diamond size={29}/><Check className="vote-check" size={13}/></> : <span>?</span>}</div></div><div className="player-name"><span className={'avatar avatar-' + i % 4}>{member.name.slice(0, 1).toUpperCase()}</span><span>{member.name}{member.id === session.userId && <small> (you)</small>}</span>{member.host && <Crown size={12}/>}</div><span className={'player-status ' + (hasVoted ? 'ready' : '')}>{!member.online ? 'Offline' : active.revealed ? hasVoted ? 'Revealed' : 'No vote' : hasVoted ? 'Card chosen' : 'Choosing a card…'}</span></div>; })}{room.members.length === 1 && <button className="invite-seat" onClick={share}><div><Plus size={20}/></div><span>Invite someone</span></button>}</div>
    {active.revealed && result ? <div className="reveal-summary"><div className="average"><span>Average</span><strong>{result.average}<small>points</small></strong></div><div className="discussion"><Sparkles size={20}/><div><strong>{result.consensus ? 'Your team agrees!' : result.count > 1 && result.min !== result.max ? 'Different cards, a good conversation.' : 'Discuss your estimate.'}</strong><p>{result.count > 1 && result.min !== result.max ? `From ${result.min?.toLocaleString('en-US')} to ${result.max?.toLocaleString('en-US')} points. What do you see differently?` : 'Agree on the final number of story points.'}</p></div></div></div> : <div className="hidden-note"><Shield size={14}/>Votes stay hidden until the reveal.</div>}
    <div className="table-controls">{session.host ? active.revealed ? <><button className="button small ghost" onClick={() => setDialog('restart')} disabled={!connected}><RotateCcw size={15}/>Vote again</button><div className="estimate-controls"><label htmlFor="estimate">Final estimate</label><select id="estimate" value={estimate} onChange={e => setEstimate(e.target.value as Value)} disabled={!connected}>{VALUES.map(v => <option key={v} value={v}>{formatPoint(v)}</option>)}</select><button className="button primary small" disabled={!connected} onClick={() => { act({ type: 'estimate', value: estimate }); setToast('Estimate saved'); }}><Check size={15}/>{active.estimate !== null ? 'Update' : 'Save estimate'}</button></div></> : <><span className="control-caption">{voted === online.length && online.length > 1 ? 'Everyone is ready. Reveal the cards!' : 'Reveal when your team is ready.'}</span><button className="button primary" onClick={() => act({ type: 'reveal' })} disabled={!connected || !Object.keys(active.votes).length}><Eye size={16}/>Reveal cards</button></> : <p className="control-caption">{active.revealed ? 'The host will save your shared estimate.' : 'The host will reveal the cards when your team is ready.'}</p>}</div>{session.host && active.estimate !== null && nextStory && <button className="next-story" onClick={() => act({ type: 'select', id: nextStory.id })} disabled={!connected}>Next story: {nextStory.title}<ArrowRight size={16}/></button>}</section>
    <section className={'your-hand ' + (active.revealed ? 'hand-complete' : '')}><div className="hand-heading"><div><span className="eyebrow">YOUR HAND</span><h2>{active.revealed ? 'A good conversation is the real win.' : 'Which power fits this story?'}</h2></div><span className="hand-selection">{active.revealed ? <><Check size={14}/>Voting closed</> : ownVote !== undefined && ownVote !== null ? <><Check size={14}/>You chose {formatPoint(ownVote)}</> : 'Choose one card'}</span></div><div className="hand-cards">{POINT_VALUES.map(value => <CreatureCard key={value} value={value} selected={ownVote === value} disabled={active.revealed || !connected} onClick={() => act({ type: 'vote', storyId: active.id, round: active.round, value })}/>)}</div><div className="hand-alternatives" aria-label="Other voting options">{(['?', '☕'] as const).map(value => <button key={value} className={'special-card ' + (ownVote === value ? 'selected' : '')} disabled={active.revealed || !connected} aria-pressed={ownVote === value} aria-label={value === '?' ? 'I am not sure yet' : 'I need a break'} onClick={() => act({ type: 'vote', storyId: active.id, round: active.round, value })}><strong aria-hidden="true">{value}</strong><span>{value === '?' ? 'Not sure' : 'Take a break'}</span></button>)}</div><p className="hand-note">{active.revealed ? 'Ready for the next challenge?' : 'You can change your card until the cards are revealed.'}</p></section></>
    : <section className="empty-arena"><div className="empty-symbol"><Swords size={34}/></div><span className="eyebrow">THE ARENA IS YOURS</span><h2>{session.host ? 'Every quest begins with a story.' : 'You are in. Let the duel begin.'}</h2><p>{session.host ? 'Add your first story and invite your team. Then everyone secretly chooses a card.' : 'The host will add the stories. Your cards will appear when a story is ready.'}</p><div className="empty-actions">{session.host && <button className="button primary" onClick={() => setDialog('story')} disabled={!connected}><Plus size={17}/>Add your first story</button>}<button className="button" onClick={share} disabled={!connected}><Link size={16}/>Share room</button></div><div className="mini-deck"><CreatureCard value="3" decorative/><CreatureCard value="5" decorative/><CreatureCard value="8" decorative/></div></section>}
    </div></div><footer className="room-footer"><span><span className={'live-dot ' + (!connected ? 'disconnected' : '')}/>{status}</span><span>{session.host ? 'You are the host. Keep this tab open.' : 'This room stays available while the host is connected.'}</span><button className="text-button" onClick={() => setDialog('leave')}><ArrowLeft size={13}/>Leave room</button></footer></main>}
    {!session && <footer className="lobby-footer"><span>BUILT FOR TEAMS. POWERED BY CREATURES.</span><span>Story Point Shodown <Diamond size={10}/> Let the cards speak.</span></footer>}
    {dialog === 'story' && <Modal title="A new story" close={() => setDialog(null)}><form onSubmit={addStory}><label>Story title<input autoFocus required value={title} maxLength={160} onChange={e => setTitle(e.target.value)} placeholder="e.g. Redesign the user experience"/></label><label>Reference <span className="optional">optional</span><input value={reference} maxLength={30} onChange={e => setReference(e.target.value)} placeholder="e.g. STORY-123"/></label><label>Description <span className="optional">optional</span><textarea value={description} maxLength={2000} rows={4} onChange={e => setDescription(e.target.value)} placeholder="What needs to be done? What context does your team need?"/></label><button className="button primary large" type="submit" disabled={!connected}><Plus size={16}/>Add story</button></form></Modal>}
    {dialog === 'help' && <Modal title="How the duel works" close={() => setDialog(null)}><ol className="help-steps"><li><strong>Open a room</strong><p>Enter your name and share the unique room link with your colleagues. Anyone with the link can join.</p></li><li><strong>Add stories and choose a card</strong><p>The host selects the active story. Everyone votes with 0.5 to 40 story points, ? when unsure, or ☕ for a break.</p></li><li><strong>Reveal, discuss and save</strong><p>Discuss the differences and agree on a final estimate. Then move on to the next story.</p></li></ol><div className="help-note"><Wifi size={19}/><p>No database: the host keeps the session in this tab. Keep it open and download the results before closing it. Closing this tab ends the room. Some corporate networks or VPNs block direct connections.</p></div></Modal>}
    {dialog === 'leave' && <Modal title="Leave the room?" close={() => setDialog(null)}><p>{session?.host ? 'You are keeping this room open. If you leave, your colleagues will lose their connection. Download the results first if you want to keep them.' : 'You are leaving the room. You can rejoin using the same link while the host stays connected.'}</p><div className="modal-actions">{room && <button className="button" onClick={download}><ArrowDownToLine size={15}/>Download results</button>}<button className="button primary" onClick={() => location.assign('/')}>Leave room</button></div></Modal>}
    {dialog === 'delete' && <Modal title="Delete story?" close={() => setDialog(null)}><p>‘{active?.title}’ and all its votes will be removed from the room.</p><div className="modal-actions"><button className="button" onClick={() => setDialog(null)}>Cancel</button><button className="button danger" disabled={!connected} onClick={() => { if (active) act({ type: 'remove', id: active.id }); setDialog(null); }}>Delete</button></div></Modal>}
    {dialog === 'restart' && <Modal title="Start a new voting round?" close={() => setDialog(null)}><p>The current votes and final estimate for this story will be cleared. Everyone will choose again in secret.</p><div className="modal-actions"><button className="button" onClick={() => setDialog(null)}>Cancel</button><button className="button primary" disabled={!connected} onClick={() => { act({ type: 'restart' }); setDialog(null); }}>Vote again</button></div></Modal>}
    {dialog === 'share' && <Modal title="Invite your team" close={() => setDialog(null)}><label>Copy this room link<input readOnly value={location.origin + '/?room=' + session?.roomId} onFocus={e => e.target.select()}/></label><p>Anyone with this link can join while you keep the room open.</p></Modal>}
    <div className={'toast ' + (toast ? 'visible' : '')} role="status" aria-live="polite">{toast && <><Check size={17}/>{toast}</>}</div>
  </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
